#page title
page_title                                : MikrotikVoucher Hotspot                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://mikrovoucher.github.com                                       # Enter Google Play Store URL.
presskit_download_link                    : https://mikrovoucher.github.com                                            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mikrotik Voucher                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Rp. 100.000                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Mikrotik Voucher mempermudah anda dalam berbisnis voucher internet

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hanif Permana                                
your_link                                 : https://mikrovoucher.github.com                     
your_city                                 : Pekalongan                                
email_address                             : sekdespermana91@gmail.com
facebook_username                         : hanifpermana                                          
instagram_username                        : hanifpermana
twitter_username                          : hanifpermana
github_username                           : mikrovoucher
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Sangat mudah digunakan
    description                           : Dengan menu yang simpel dan mudah sekali digunakan
    fontawesome_icon_name                 : magic
    
  - title                                 : Android Support
    description                           : Pedoman kami ( The World in Your Hand ) dengan menggunakan produk kami. semakin mudah dan cepat pula anda mengelola hotspot mikrotik anda.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Kami pula menyediakan video tutorial penggunaan, apabila anda kebingungan menggunakan produk kami
    fontawesome_icon_name                 : play-circle

  - title                                 : Mudah di gunakan
    description                           : Memungkinankan anda menggunakan dengan mudah aplikasi kami.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Banyak Sekali feature kami yang perlu anda ketahui
    fontawesome_icon_name                 : star

  - title                                 : Hubungi Kami
    description                           : Hubungi kami di sosial media kami.
    fontawesome_icon_name                 : link

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown